HISTORY = [(u'First reported African slaves in The New World', 1502),
(u'A period of drought, with famine in all of Spain.', 1504),
(u'Leonardo da Vinci completes the Mona Lisa.', 1506),
(u'Christopher Columbus dies in Valladolid, Spain.', 1506),
(u'Michelangelo paints the Sistine Chapel ceiling.', 1508),
(u'D\xf3zsa rebellion (peasant revolt) in Hungary.', 1514),
(u'Leonardo da Vinci dies of natural causes on May 2.', 1519),
(u'Sweden gains independence from the Kalmar Union.', 1523),
(u"German Peasants' War in the Holy Roman Empire.", 1524),
(u'Protestant Reformation begins in Sweden.', 1527),
(u'Anne Boleyn becomes Queen of England.', 1533),
(u'Elizabeth Tudor is born.', 1533),
(u'Jacques Cartier claims Quebec for France.', 1534),
(u'The Ottomans capture Baghdad.', 1534),
(u'Establishment of the Inquisition in Portugal', 1536),
(u'Gonzalo Jim\xe9nez de Quesada founds Bogot\xe1.', 1538),
(u'Hernando de Soto explores inland North America.', 1539),
(u'Pedro de Valdivia founds Santiago de Chile.', 1541),
(u'Sahib I Giray of Crimea invades Russia.', 1541),
(u'Songhai forces sack the Malian capital of Niani', 1545),
(u'Portuguese found a settlement at Macau.', 1553),
(u'Russia conquers the Astrakhan Khanate.', 1556),
(u'Elizabeth Bathory is born in Nyirbator, Hungary.', 1560),
(u'Sir Francis Bacon is born in London.', 1561),
(u'Galileo Galilei born on February 15', 1564),
(u'William Shakespeare baptized 26 April', 1564),
(u'Mir Chakar Khan Rind died age of 97.', 1565),
(u'Morisco Revolt in Spain.', 1568),
(u'The Azuchi-Momoyama period in Japan.', 1568),
(u'Rising of the North in England.', 1569),
(u'Oda Nobunaga finally captures Nagashima fortress.', 1575),
(u'Tahmasp I, Safavid king, died.', 1576),
(u'Sack of Antwerp by badly paid Spanish soldiers.', 1576),
(u'Francis Drake circles the world.', 1577),
(u'Death of Sultan Baabullah of Ternate.', 1583),
(u'Colony at Roanoke founded in North America', 1585),
(u'England repulses the Spanish Armada.', 1588),
(u'Spain repulses the English Armada.', 1589),
(u'Birth of Ren\xe9 Descartes.', 1596),
(u'The Mali Empire is defeated at the Battle of Jenn\xe9', 1599),
(u'Modern square root symbol (\u221a)', 1525),
(u'William Lee invents the stocking frame.', 1589),
(u'Galileo Galilei invents a thermometer.', 1593),
(u'William Barents discovers Spitsbergen.', 1596),
(u'Opera in Florence by Jacopo Peri.', 1597),
(u'Gunpowder Plot failed in England.', 1605),
(u'Assassination of Stephen Bocskay of Transylvania.', 1606),
(u'A Spanish fleet occupies Ternate and Tidore.[4]', 1606),
(u'Matteo Ricci dies in Beijing.', 1610),
(u'Death of retired Shogun Tokugawa Ieyasu.', 1616),
(u'The Defenestration of Prague.', 1618),
(u'Bethlen Gabor is defeated outside Vienna.', 1619),
(u'Polish-Ottoman War over Moldavia.', 1620),
(u"St. Peter's Basilica in the Vatican completed.", 1626),
(u'Aurochs go extinct.', 1627),
(u'Abbas I, the Safavids king, died.', 1629),
(u'Mount Vesuvius erupts.', 1631),
(u'Taj Mahal building work started in Agra, India.', 1632),
(u'Japan transforms into "locked country".', 1633),
(u'Battle of N\xf6rdlingen results in Catholic victory.', 1634),
(u'Qing dynasty attacked Joseon dynasty.', 1637),
(u'Torture is outlawed in England.', 1640),
(u'The Irish Rebellion.', 1641),
(u'The Mauritanian Thirty-Year War.', 1644),
(u'Seven-year-old Mehmed IV becomes sultan.', 1647),
(u'The Great Plague of Seville.', 1647),
(u'Fronde civil war in France.', 1648),
(u'The Cromwellian conquest of Ireland.', 1649),
(u'Mehmed K\xf6pr\xfcl\xfc is Grand Vizier.', 1654),
(u'The reign of the Kangxi Emperor of China begins.', 1661),
(u'Cardinal Mazarin, de-facto ruler of France, dies.', 1661),
(u'Ottoman war against Habsburg Hungary.', 1663),
(u'Robert Hooke discovers cells using a microscope.', 1663),
(u'The Great Plague of London.', 1665),
(u'The Great Fire of London.', 1666),
(u'The Ottomans capture Crete.', 1669),
(u"The Hudson's Bay Company is founded in Canada.", 1670),
(u'Polish-Ottoman War.', 1672),
(u'Franco-Dutch War.', 1672),
(u'Maratha Empire founded in India by Shivaji.', 1674),
(u'Kara Mustafa becomes Grand Vizier.', 1676),
(u'The Ottomans make camp at Adrianople.', 1682),
(u'A Habsburg council of war is held in Vienna.', 1683),
(u'The Siege of Derry.', 1688),
(u'The War of the Two Kings in Ireland.', 1688),
(u'The Battle of the Boyne in Ireland.', 1690),
(u'Salem witch trials in Massachusetts.', 1692),
(u'Famine in France kills 2 million.[9]', 1692),
(u'The Bank of England is established.', 1694),
(u'Mary II of England dies.', 1694),
(u'Grand Embassy of Peter the Great', 1697),
(u'Supernova SN 1604 is observed in the Milky Way.', 1604),
(u'Dutch Bible published.', 1637),
(u'Giovanni Riccioli renames the lunar maria.', 1651),
(u'Antoni van Leeuwenhoek discovers Bacteria.', 1676),
(u'First measurement of the speed of light.', 1676),
(u'Kingdom of Prussia declared under King Frederick I', 1701),
(u'Ashanti Empire is formed under Osei Kofi Tutu I', 1701),
(u'Camisard Rebellion in France.', 1702),
(u"End of Japan's Genroku period.", 1704),
(u'First Javanese War of Succession.[7]', 1704),
(u"Handel's first opera, Almira, premieres.", 1705),
(u'Great Frost of 1709, coldest winter in 500 years.', 1709),
(u'Hotaki dynasty founded in Afghanistan.', 1709),
(u'Surabaya rebels against the VOC.[10]', 1717),
(u'Tulip period of the Ottoman Empire', 1718),
(u'Second Javanese War of Succession.[10]', 1719),
(u'The South Sea Bubble', 1720),
(u'The Great Plague of Marseille', 1720),
(u'Peter I reforms the Russian Orthodox Church', 1721),
(u'Kangxi Emperor of China dies', 1722),
(u'Russo-Persian War', 1722),
(u'Anglo-Spanish War', 1727),
(u'Crimean Tatar raids into Russia.[13]', 1732),
(u'War of the Polish Succession.', 1733),
(u'Russo-Turkish War.', 1735),
(u"Turlough O'Carolan, famous Irish harper, died.", 1738),
(u'Frederick the Great comes to power in Prussia', 1740),
(u'War of the Austrian Succession', 1740),
(u'Russians began settling the Aleutian Islands', 1741),
(u'Peak of the Little Ice Age', 1750),
(u'The Lisbon earthquake', 1755),
(u'George III became King of Britain.', 1760),
(u'Zand dynasty founded in Iran', 1760),
(u'Maratha Empire defeated at Battle of Panipat', 1761),
(u'Reign of Catherine the Great of Russia.', 1762),
(u'Kingdom of Mysore conquers the Kingdom of Keladi', 1763),
(u'Anglo-Mysore Wars', 1766),
(u'Burmese conquered the Ayutthaya kingdom.', 1767),
(u'Gurkhas conquered Nepal.', 1768),
(u'War of the Bar Confederation', 1768),
(u'Russo-Turkish War', 1768),
(u'The Plague Riot in Moscow.', 1771),
(u'First Anglo-Maratha War', 1775),
(u'American Revolutionary War', 1775),
(u'Illuminati founded by Adam Weishaupt', 1776),
(u'Adam Smith published The Wealth of Nations', 1776),
(u'T\xe2y S\u01a1n Dynasty established in Vietnam.', 1778),
(u'Spanish settlers founded Los Angeles.', 1781),
(u'Russian Empire annexed the Crimean Khanate.', 1783),
(u'Russo-Turkish War', 1787),
(u'Russo-Swedish War (1788\u20131790)', 1788),
(u'The French Revolution', 1789),
(u'The Li\xe8ge Revolution', 1789),
(u'The Brabant Revolution', 1789),
(u'Establishment of the Polish-Prussian Pact', 1790),
(u'The Haitian Revolution', 1791),
(u'New York Stock & Exchange Board founded.', 1792),
(u'Polish\u2013Russian War of 1792', 1792),
(u'March, Hamengkubuwana I dies.[26]', 1792),
(u'Upper Canada bans slavery.', 1793),
(u'Polish revolt', 1794),
(u'Mohammad Khan Qajar razes Tbilisi to the ground.', 1795),
(u'British ejected Dutch from Ceylon.', 1796),
(u'Quasi-War between the United States and France.', 1798),
(u'Dutch East India Company is dissolved.', 1799),
(u'The first piano was built by Bartolomeo Cristofori', 1709),
(u'The Tuning fork was invented by John Shore', 1711),
(u'The Steam Engine invented by Thomas Newcomen', 1712),
(u'Flying shuttle invented by John Kay', 1733),
(u'Vitus Bering discovers Alaska', 1741),
(u'The Lightning rod invented by Benjamin Franklin', 1752),
(u'The Steamboat invented by Claude de Jouffroy', 1776),
(u'The Circular saw invented by Samuel Miller', 1777),
(u'William Herschel announces discovery of Uranus', 1781),
(u'The Bifocals invented by Benjamin Franklin', 1784),
(u'The Argand lamp invented by Aim\xe9 Argand[31]', 1784),
(u'The Power loom invented by Edmund Cartwright', 1785),
(u'The Automatic flour mill invented by Oliver Evans', 1785),
(u'The Threshing machine invented by Andrew Meikle', 1786),
(u"Jacques Charles discovers Charles's Law", 1787),
(u"Rosetta stone discovered by Napoleon's troops", 1799),
(u'A Tale of a Tub by Jonathan Swift first published', 1704),
(u'Robinson Crusoe by Daniel Defoe', 1719),
(u'The New Science by Giambattista Vico', 1725),
(u"Gulliver's Travels by Jonathan Swift", 1726),
(u'Clarissa by Samuel Richardson', 1748),
(u'The French Encyclop\xe9die', 1751),
(u'Candide by Voltaire', 1759),
(u'The Theory of Moral Sentiments by Adam Smith', 1759),
(u'Tristram Shandy by Laurence Sterne', 1759),
(u'Emile: or, On Education by Jean-Jacques Rousseau', 1762),
(u'Amazing Grace published by John Newton', 1779),
(u'The Robbers by Friedrich Schiller first published', 1781),
(u'Critique of Practical Reason by Immanuel Kant', 1788),
(u'Songs of Innocence by William Blake', 1789),
(u'Rights of Man by Thomas Paine', 1791),
(u'Songs of Experience by William Blake', 1794),
(u'Brandenburg concertos by J.S. Bach', 1721),
(u'St John Passion by J.S. Bach', 1724),
(u'St Matthew Passion composed by J.S. Bach', 1727),
(u'Messiah, oratorio by Handel premiered in Dublin', 1742),
(u'The Art of Fugue by J.S. Bach', 1751),
(u'The Marriage of Figaro, opera by Mozart', 1786),
(u'Don Giovanni, opera by Mozart', 1787),
(u'The Magic Flute, opera by Mozart', 1791),
(u'London symphonies by Haydn', 1791),
(u'The Creation, oratorio by Haydn first performed', 1798),
(u'Ranjit Singh crowned as King of Punjab.', 1801),
(u'Cairo falls to the British.', 1801),
(u'Assassination of Tsar Paul I of Russia.', 1801),
(u'First phase of Padri War. (to 1825)', 1803),
(u'Russo-Persian War.', 1804),
(u'Austrian Empire founded by Francis I.', 1804),
(u'Napoleon crowns himself Emperor of the French.', 1804),
(u'World population reaches 1 billion.', 1804),
(u'First steam locomotive begins operation.', 1804),
(u'Morphine first isolated.', 1804),
(u'Fulani Jihad in Nigeria.', 1804),
(u'Muhammad Ali modernizes Egypt.', 1805),
(u'Cape Colony becomes part of the British Empire.', 1806),
(u'Russo-Turkish War, Treaty of Bucharest.', 1806),
(u'Britain declares the Slave Trade illegal.', 1807),
(u'Beethoven performs his Fifth Symphony', 1808),
(u'Spanish guerrillas fight in the Peninsular War.', 1808),
(u'The trumpet gets valves.', 1810),
(u'Jane Austen publishes Pride and Prejudice', 1813),
(u'Napoleon abdicates and is exiled to Elba.', 1814),
(u'Elisha Collier invents the Flintlock Revolver.', 1814),
(u'Jane Austen publishes Emma in December.', 1815),
(u'Independence of Argentina.', 1816),
(u'First Seminole War begins in Florida.', 1817),
(u'Russia commences its conquest of the Caucasus.', 1817),
(u'Mary Shelley publishes Frankenstein.', 1818),
(u'Independence of Chile.', 1818),
(u'John Keats writes his odes of 1819.', 1819),
(u'Peterloo massacre in England.', 1819),
(u'Missouri Compromise.', 1820),
(u'Regency period ends in the United Kingdom.', 1820),
(u'Discovery of Antarctica.', 1820),
(u'Dissolution of the Maratha Empire.', 1820),
(u'Peru declares its independence from Spain.', 1821),
(u'Navarino Massacre.', 1821),
(u"Premiere of Beethoven's Ninth Symphony.", 1824),
(u'Cadbury is established in Birmingham.', 1824),
(u'First isolation of aluminum.', 1825),
(u'Independence of Bolivia.', 1825),
(u'The Decembrist revolt.', 1825),
(u'Java War. (to 1830)', 1825),
(u'Death of William Blake, Ludwig van Beethoven', 1827),
(u"Johann Wolfgang von Goethe's Faust premieres.", 1829),
(u'First electric motor built.', 1829),
(u'July Revolution in France.', 1830),
(u'November Uprising in Poland against Russia.', 1830),
(u'France invades and occupies Algeria.', 1831),
(u"Charles Darwin's journey on the HMS Beagle.", 1831),
(u'Egyptian\u2013Ottoman War.', 1831),
(u'Second phase of Padri War. (to 1838)', 1831),
(u'Carlist Wars in Spain.', 1833),
(u'The German Customs Union is formed.', 1834),
(u'Spanish Inquisition officially ends.', 1834),
(u'Telegraphy patented.', 1837),
(u'Charles Dickens publishes Oliver Twist.', 1837),
(u'Death of Alexander Pushkin.', 1837),
(u'Rebellions of 1837 in Canada.', 1837),
(u'Kingdom of Belgium declared.', 1839),
(u'Uruguayan Civil War.', 1839),
(u'The word "dinosaur" is coined by Richard Owen', 1841),
(u'Treaty of Nanking cedes Hong Kong to the British.', 1842),
(u'Anaesthesia used for the first time.', 1842),
(u'The first wagon train sets out from Missouri.', 1843),
(u'The great auk is rendered extinct.', 1844),
(u'Dominican War of Independence from Haiti.', 1844),
(u'Lunacy Act 1845 passes through Parliament.', 1845),
(u'First Anglo-Sikh War.', 1845),
(u'The New Zealand Land Wars.', 1845),
(u'Mormon migration to Utah.', 1846),
(u'The Caste War of Yucat\xe1n.', 1847),
(u'Second Anglo-Sikh War', 1848),
(u'The Communist Manifesto published.', 1848),
(u'Revolutions of 1848 in Europe.', 1848),
(u'California Gold Rush.', 1848),
(u'The safety pin and the gas mask are invented.', 1849),
(u'The Little Ice Age ends around this time.', 1850),
(u'Louis Napoleon assumes power in France in a coup.', 1851),
(u'Victorian gold rush in Australia', 1851),
(u'Herman Melville publishes Moby-Dick.', 1851),
(u'Cocaine is isolated by Friedrich Gaedcke.', 1855),
(u"World's first oil refinery in Romania", 1856),
(u'British Empire in India lasts for 90 years.', 1858),
(u'Construction of Big Ben is completed.', 1858),
(u'Charles Darwin publishes On the Origin of Species.', 1859),
(u'Suez Canal is constructed.', 1859),
(u'The Pony Express started.', 1860),
(u'Russia abolishes serfdom.', 1861),
(u'Death of Prince Albert.', 1861),
(u'The Pony Express ended.', 1862),
(u'Victor Hugo publishes Les Mis\xe9rables.', 1862),
(u'French gain first foothold in Southeast Asia.', 1862),
(u'Muslim Rebellion in north-west China.', 1862),
(u'First section of the London Underground opens.', 1863),
(u'France annexes Cambodia.', 1863),
(u'Polish uprising against the Russian Empire.', 1863),
(u'Circassian Genocide.(21 May 1864)', 1864),
(u'Gregor Mendel formulates his laws of inheritance.', 1865),
(u'Famine in Finland.', 1866),
(u'The United States purchases Alaska from Russia.', 1867),
(u'Canadian Confederation formed.', 1867),
(u'Alfred Nobel invents dynamite.', 1867),
(u'Cro-Magnon man first identified.', 1868),
(u"Ten Years' War between Cuba and Spain.", 1868),
(u'Leo Tolstoy publishes War and Peace.', 1869),
(u'Dmitri Mendeleev created the Periodic table.', 1869),
(u'Second Industrial Revolution', 1871),
(u'Royal Albert Hall opens in London.', 1871),
(u'The feudal system is dismantled in Japan.', 1871),
(u'The Panic of 1873 starts the "Long Depression".', 1873),
(u'The samurai class is abolished in Japan.', 1873),
(u'Blue jeans and barbed wire are invented.', 1873),
(u'The Home Rule Movement is established in Ireland.', 1874),
(u'The British East India Company is dissolved.', 1874),
(u'First Republic in Spain.', 1874),
(u'26 million Indians perish in India due to famine.', 1875),
(u"Georges Bizet's opera Carmen premiers in Paris.", 1875),
(u'Queen Victoria becomes Empress of India.', 1876),
(u'Crazy Horse surrenders and is later killed', 1877),
(u'Asaph Hall discovers the moons of Mars', 1877),
(u'Thomas Edison invents the phonograph', 1877),
(u'Anglo-Zulu War in South Africa. - South Africa', 1879),
(u'Thomas Edison tests his first light bulb.', 1879),
(u'the First Boer War.', 1880),
(u'Tsar Alexander II is assassinated.', 1881),
(u'Wave of pogroms begins in the Russian Empire.', 1881),
(u'President James A. Garfield is assassinated.', 1881),
(u'The Mahdist War in Sudan.', 1881),
(u'The quagga is rendered extinct.', 1883),
(u'Siege of Khartoum.', 1884),
(u'Germany gains control of Cameroon.', 1884),
(u'Karl Benz sells the first commercial automobile.', 1886),
(u'The British Empire takes over Balochistan.', 1887),
(u'Slavery banned in Brazil.', 1888),
(u'Eiffel Tower is inaugurated in Paris.', 1889),
(u'Vincent van Gogh paints Starry Night.', 1889),
(u'Aspirin patented.', 1889),
(u'Moulin Rouge opens in Paris.', 1889),
(u'Italy annexes Eritrea.', 1890),
(u'Independence of Luxembourg.', 1890),
(u'Death of Vincent van Gogh.', 1890),
(u'The cardboard box is invented.', 1890),
(u'1891 Chilean Civil War.', 1891),
(u'Wrigley Company is founded in Illinois.', 1891),
(u'Basketball is invented.', 1892),
(u'US forces overthrow the government of Hawaii.', 1893),
(u'First gramophone record.', 1894),
(u'Karl Elsener invents the Swiss Army knife.', 1894),
(u'Dreyfuss Affair in France.', 1894),
(u'Volleyball is invented.', 1895),
(u'French troops capture Antananarivo in Madagascar.', 1895),
(u'Wilhelm R\xf6ntgen identifies x-rays.', 1895),
(u'Olympic Games revived in Athens.', 1896),
(u'Ethiopia defeated Italy at the Battle of Adwa.', 1896),
(u'Klondike Gold Rush in Canada.', 1896),
(u'Benin Expedition of 1897 loots and burns Benin.', 1897),
(u'Greco-Turkish War.', 1897),
(u'Bram Stoker writes Dracula.', 1897),
(u'H. G. Wells publishes The War of the Worlds', 1898),
(u'Second Boer War begins.', 1899),
(u'Philippine\u2013American War begins.', 1899),
(u'Indian famine kills over 1 million people.', 1899),
(u'Boxer Rebellion ends.', 1901),
(u'Assassination of William McKinley.', 1901),
(u'Second Boer War ends.', 1902),
(u'Philippine\u2013American War ends.', 1902),
(u'Cuba gains independence from the United States.', 1902),
(u'Unification of Saudi Arabia begins.', 1902),
(u'Pius X becomes Pope.', 1903),
(u'The teddy bear is invented.', 1903),
(u'The first Tour de France is held.', 1903),
(u'Trans-Siberian railway is completed.', 1904),
(u'Construction of the Panama Canal begins.', 1904),
(u'End of British expedition to Tibet.', 1904),
(u'Russo-Japanese War ends.', 1905),
(u'Revolution of 1905 in Russia.', 1905),
(u'Persian Constitutional Revolution begins.', 1905),
(u'Trans-Siberian Railway opened.', 1905),
(u"Albert Einstein's formulation of relativity.", 1905),
(u'Schlieffen Plan proposed.', 1905),
(u'First Moroccan Crisis.', 1905),
(u'Dreyfus Affair ends.', 1906),
(u'Death of Paul C\xe9zanne.', 1906),
(u'The US began the Second Occupation of Cuba.', 1906),
(u'Herero and Namaqua Genocide ends.', 1907),
(u'Japan\u2013Korea Treaty of 1907.', 1907),
(u'First commercial radio transmissions.', 1908),
(u'Young Turk Revolution in the Ottoman Empire.', 1908),
(u'Independence of Bulgaria.', 1908),
(u'1908 Messina earthquake kills over 70,000 people.', 1908),
(u'United States troops leave Cuba.', 1909),
(u'Anglo-Siamese Treaty of 1909.', 1909),
(u'Ottoman countercoup fails in the Ottoman Empire.', 1909),
(u'Japan and China sign the Jiandao/Gando Treaty.', 1909),
(u'Beginning of the Mexican Revolution.', 1910),
(u'Union of South Africa created.', 1910),
(u'Imperial Japan annexes Korea.', 1910),
(u'Deaths of Leo Tolstoy and Mark Twain.', 1910),
(u'Boy Scouts of America is founded.', 1910),
(u"Halley's Comet returns.", 1910),
(u'Montenegro is proclaimed an independent kingdom.', 1910),
(u'Albanian Revolt of 1910.', 1910),
(u'Roald Amundsen first reaches the South Pole.', 1911),
(u'New Delhi becomes the capital of British India.', 1911),
(u'Ernest Rutherford identifies the atomic nucleus.', 1911),
(u'Agadir Crisis.', 1911),
(u'The African National Congress is founded.', 1912),
(u'Morocco becomes a protectorate of France.', 1912),
(u'Sinking of the RMS Titanic.', 1912),
(u'First Balkan War begin.', 1912),
(u'United States occupation of Nicaragua begins.', 1912),
(u'La Decena Tr\xe1gica.', 1913),
(u'Treaty of London.', 1913),
(u'Second Balkan War and Treaty of Bucharest.', 1913),
(u'The Federal Reserve System is created.', 1913),
(u'Panama Canal opens.', 1914),
(u'Benedict XV becomes Pope.', 1914),
(u'Martha, last known passenger pigeon, dies.', 1914),
(u'The RMS Lusitania is sunk.', 1915),
(u'The United States occupation of Haiti begins.', 1915),
(u'Armenian genocide in the Ottoman Empire.', 1915),
(u'Easter Rising in Ireland.', 1916),
(u'The implementation of daylight saving time.', 1916),
(u'Warlord Era begins in China.', 1916),
(u'The Gallipoli Campaign fails.', 1916),
(u'Battle of the Somme.', 1916),
(u'Battle of Verdun.', 1916),
(u'The Arab Revolt begins.', 1916),
(u'The first Pulitzer Prizes are awarded.', 1917),
(u'October Revolution in Russia.', 1917),
(u'Ukrainian\u2013Soviet War begins.', 1917),
(u'End of World War I. German Revolution begins.', 1918),
(u'Murder of Tsar Nicholas II and his family.', 1918),
(u'Finnish Civil War.', 1918),
(u'Partitioning of the Ottoman Empire begins.', 1918),
(u'The British occupy Palestine.', 1918),
(u'Mutawakkilite Kingdom of Yemen is founded.', 1918),
(u'Azerbaijan Democratic Republic is declared.', 1918),
(u'Armenian\u2013Azerbaijani War begins.', 1918),
(u'Polish\u2013Ukrainian War begins.', 1918),
(u'Treaty of Versailles redraws European borders.', 1919),
(u'League of Nations founded in Paris.', 1919),
(u'Polish-Soviet War begins.', 1919),
(u'Comintern established.', 1919),
(u'Egyptian Revolution of 1919.', 1919),
(u'Turkish War of Independence begins.', 1919),
(u'End of Polish\u2013Ukrainian War.', 1919),
(u'Ernest Rutherford discovers the proton.', 1919),
(u'Mexican Revolution ends.', 1920),
(u'Greece restores its monarchy after a referendum.', 1920),
(u'Mohandas Gandhi launches Non-cooperation movement.', 1920),
(u'Prohibition in the United States enforced.', 1920),
(u'Coup brings the Pahlavi dynasty to power in Iran.', 1921),
(u'The Irish Civil War begins.', 1922),
(u'The Italian reconquest of Libya begins.', 1922),
(u"Howard Carter discovers Tutankhamen's tomb.", 1922),
(u'Pius XI becomes Pope.', 1922),
(u'James Joyce publishes Ulysses.', 1922),
(u'The Washington Naval Treaty is signed.', 1922),
(u'Time Magazine is first published.', 1923),
(u'Irish Civil War ends.', 1923),
(u'The Walt Disney Company is founded.', 1923),
(u'The Caliphate is abolished by Kamal Atat\xfcrk.', 1924),
(u'George Gershwin composes Rhapsody In Blue.', 1924),
(u'Mein Kampf is published.', 1925),
(u'Locarno Treaties are signed.', 1925),
(u'Serum run to Nome.', 1925),
(u'Hirohito becomes Emperor of Japan.', 1926),
(u'The Jazz Singer, the first "talkie", is released.', 1927),
(u'Joseph Stalin becomes leader of the Soviet Union.', 1927),
(u'Chinese Civil War begins.', 1927),
(u'Bath School disaster.', 1927),
(u'Saudi Arabia gains independence.', 1927),
(u'World population reaches 2 billion.', 1927),
(u"Charles Lindbergh's flight to Paris.", 1927),
(u'Discovery of penicillin by Alexander Fleming.', 1928),
(u'Warlord Era ends in China.', 1928),
(u'Malta becomes a British Dominion.', 1928),
(u'Bubble gum is invented.', 1928),
(u'King Zog I is crowned in Albania.', 1928),
(u'The Kellogg-Briand Pact is signed in Paris.', 1928),
(u'Mickey Mouse is created at the Walt Disney Studio.', 1928),
(u'Hassan al-Banna founds the Muslim Brotherhood.', 1928),
(u'Vatican City is recognised as a sovereign state.', 1929),
(u"Saint Valentine's Day Massacre.", 1929),
(u'The first Academy Awards are presented.', 1929),
(u'Clyde Tombaugh discovers Pluto.', 1930),
(u'Haile Selassie becomes king of Abyssinia.', 1930),
(u'First FIFA World Cup hosted.', 1930),
(u'Floods in China kill up to 2.5 million people.', 1931),
(u'Independence of South Africa.', 1931),
(u'Construction of the Empire State Building.', 1931),
(u'The Second Spanish Republic is declared.', 1931),
(u'Military coup in Chile.', 1932),
(u'BBC World Service starts broadcasting.', 1932),
(u'The Neutron is discovered.', 1932),
(u'Lindbergh baby kidnapping.', 1932),
(u'Adolf Hitler becomes Chancellor of Germany.', 1933),
(u'New Deal begins in America.', 1933),
(u'United States occupation of Nicaragua ends.', 1933),
(u'Prohibition in the United States is abolished.', 1933),
(u'Dictatorships begin in Brazil and Bolivia.', 1934),
(u'Mao Zedong begins the Long March.', 1934),
(u'United States occupation of Haiti ends.', 1934),
(u'Persia becomes Iran.', 1935),
(u'Enactment of the Nuremberg racial laws.', 1935),
(u'Beginning of the Spanish Civil War.', 1936),
(u'Great Purge begins under Stalin.', 1936),
(u'Hoover Dam is completed.', 1936),
(u'Italy annexes Ethiopia.', 1936),
(u'Rape of Nanking.', 1937),
(u'Deaths of George Gershwin and Maurice Ravel.', 1937),
(u'Anschluss unifies Germany and Austria.', 1938),
(u'Great Purge ends after nearly 700,000 executions.', 1938),
(u'DC Comics hero Superman has its first appearance.', 1938),
(u'Soviet invasion of Poland begins 16 days later.', 1939),
(u'Palestinian revolt against the British ends.', 1939),
(u'Pius XII becomes Pope.', 1939),
(u'Winter War between Soviet Union and Finland.', 1940),
(u'Soviet Union annexes the Baltic states.', 1940),
(u'The Blitz begins.', 1940),
(u'Leon Trotsky is assassinated.', 1940),
(u'Chechen insurgency begins in Soviet Union.', 1940),
(u'Siege of Leningrad begins.', 1941),
(u'Battle of Midway.', 1942),
(u'Battle of the Coral Sea.', 1942),
(u'First and second Battles of El Alamein.', 1942),
(u'Manhattan Project begins.', 1942),
(u'Warsaw Ghetto uprising fails.', 1943),
(u'Green Revolution begins.', 1943),
(u'D-Day.', 1944),
(u'Death of Edvard Munch.', 1944),
(u'Bombing of Dresden.', 1945),
(u'Battle of Berlin.', 1945),
(u'Yalta Conference.', 1945),
(u'End of World War II in Europe.', 1945),
(u'United Nations founded.', 1945),
(u'Independence of Korea.', 1945),
(u'Deaths of Anne Frank and B\xe9la Bart\xf3k.', 1945),
(u'Independence of Indonesia.', 1945),
(u'Nuremberg trials begin.', 1945),
(u'Italy becomes a republic.', 1946),
(u'French Fourth Republic established.', 1946),
(u'Independence of Jordan.', 1946),
(u'Nuremberg trials end.', 1946),
(u'First Indochina War begins.', 1946),
(u'First images taken of the Earth from space.', 1946),
(u'Bhumibol Adulyadej becomes King of Thailand.', 1946),
(u'Treaty of Manila declares Philippines independent.', 1946),
(u'Invention of the first practical transistor.', 1947),
(u'Breaking of the sound barrier.', 1947),
(u'Creation of the U.S. Central Intelligence Agency.', 1947),
(u'Arab-Israeli War.', 1948),
(u'Berlin Blockade begins.', 1948),
(u'Assassination of Mohandas Gandhi.', 1948),
(u'The independence of Burma.', 1948),
(u'Beginning of apartheid in South Africa.', 1948),
(u'Division of North and South Korea.', 1948),
(u'First Indo-Pakistani War ends.', 1948),
(u'Creation of NATO. Berlin Blockade ends.', 1949),
(u'COMECON founded by USSR and the Eastern Bloc.', 1949),
(u'Partition of Kashmir.', 1949),
(u'Soviet Union tests atomic bomb.', 1949),
(u'Beginning of the Korean War.', 1950),
(u'Colombo Plan comes into effect.', 1951),
(u'European Defence Community formed.', 1952),
(u'Slansky Trial in Czechoslovakia.', 1952),
(u'Detonation of the hydrogen bomb.', 1952),
(u'First scheduled flight by commercial jet.', 1952),
(u'Mau Mau Uprising begins in Kenya.', 1952),
(u'Independence of Cambodia.', 1953),
(u'Mohammed Mossadeq deposed in Iran.', 1953),
(u'End of the Korean War.', 1953),
(u"Elvis Presley's musical career is launched.", 1953),
(u'First Indochina War ends.', 1954),
(u'Algerian War begins.', 1954),
(u'First Taiwan Strait Crisis begins.', 1954),
(u'Signing of the Warsaw Pact.', 1955),
(u'First Sudanese Civil War begins.', 1955),
(u'First Taiwan Strait Crisis ends.', 1955),
(u'Antimatter first produced.', 1955),
(u'Formation of the Central Treaty Organization.', 1955),
(u'French Fifth Republic established.', 1956),
(u'The Hungarian Uprising crushed by Soviet troops.', 1956),
(u'Brasilia constructed.', 1956),
(u'Independence of Ghana.', 1957),
(u'Harold Macmillan become British Prime Minister.', 1957),
(u'Great Chinese Famine begins in China.', 1958),
(u"CND's symbol, the peace sign, is first used.", 1958),
(u'Second Taiwan Strait Crisis.', 1958),
(u'Cuban Revolution.', 1959),
(u'Independence of Cyprus and Singapore.', 1959),
(u'First documented AIDS cases.', 1959),
(u'Beginning of the Vietnam War.', 1959),
(u'First images of the far side of the Moon.', 1959),
(u'World population reaches 3 billion.', 1959),
(u'European Free Trade Association formed.', 1960),
(u'Sharpeville Massacre in South Africa.', 1960),
(u'Mau Mau Uprising ends.', 1960),
(u'Construction of the first laser.', 1960),
(u'The Beatles form in Liverpool.', 1960),
(u'Muhammad Ali wins gold in Rome.', 1960),
(u'Construction of the Berlin Wall.', 1961),
(u'First human spaceflight.', 1961),
(u'Cuban missile crisis.', 1962),
(u'Death of Marilyn Monroe.', 1962),
(u'Indonesia\u2013Malaysia confrontation begins.', 1962),
(u'North Yemen Civil War begins.', 1962),
(u'Sino-Indian War.', 1962),
(u'Martin Luther King, Jr.', 1963),
(u'Assassination of John F. Kennedy.', 1963),
(u'Launch of the first geostationary satellite.', 1963),
(u'Paul VI becomes Pope.', 1963),
(u'Independence of Malta, Malawi and Tanzania.', 1964),
(u'The Beatles first visit to the United States.', 1964),
(u'Rhodesian Bush War begins.', 1964),
(u'First close-up images of Mars.', 1964),
(u'Second Indo-Pakistani War.', 1965),
(u'Second Vatican Council is closed by Pope Paul VI.', 1965),
(u'Indonesia\u2013Malaysia confrontation ends.', 1966),
(u"China's Cultural Revolution begins.", 1966),
(u'Independence of Lesotho, Botswana and Barbados.', 1966),
(u'Summer of Love.', 1967),
(u'Six Day War.', 1967),
(u'ASEAN founded.', 1967),
(u'The Beatles release their landmark album Sgt.', 1967),
(u"Pepper's Lonely Hearts Club Band.", 1967),
(u'Assassinations of Martin Luther King, Jr.', 1968),
(u'May 1968 protests in France.', 1968),
(u'The Troubles begin in Northern Ireland.', 1968),
(u'Tet Offensive occurs in South Vietnam.', 1968),
(u'Moon landings.', 1969),
(u'Woodstock festival.', 1969),
(u'Sino-Soviet border conflict.', 1969),
(u'The Manson Family Murders.', 1969),
(u'Polish 1970 protests.', 1970),
(u'Cambodian Civil War begins.', 1970),
(u'Yemeni Civil War ends.', 1970),
(u'Maiden flight of the Boeing 747.', 1970),
(u'Black September in Jordan begins.', 1970),
(u'Death of Gamal Abdel Nasser.', 1970),
(u'Anwar Sadat becomes President of Egypt.', 1970),
(u'Deaths of Jimi Hendrix and Janis Joplin.', 1970),
(u'Black September in Jordan ends.', 1971),
(u'Internment begins in Northern Ireland.', 1971),
(u'Invention of the microchip.', 1971),
(u'Idi Amin seizes power in Uganda.', 1971),
(u'Greenpeace founded.', 1971),
(u'COINTELPRO officially ends.', 1971),
(u"Northern Ireland's Bloody Sunday.", 1972),
(u'First Sudanese Civil War ends.', 1972),
(u"1973 Chilean coup d'\xe9tat.", 1973),
(u'First space station, Skylab, is launched.', 1973),
(u'Wade.', 1973),
(u'Death of Pablo Picasso.', 1973),
(u'First close-up images of Jupiter.', 1973),
(u'The Sears Tower is completed.', 1973),
(u'Turkish occupation of Cyprus.', 1974),
(u'First close-up images of Mercury.', 1974),
(u'World population reaches 4 billion.', 1974),
(u'Resignation of Richard Nixon.', 1974),
(u'End of Vietnam War and Fall of Saigon.', 1975),
(u'Haile Selassie I dies in mysterious circumstances.', 1975),
(u'Dmitri Shostakovich dies.', 1975),
(u'The Killing Fields murders begin.', 1975),
(u'First Cricket World Cup hosted.', 1975),
(u'First outbreak of the Ebola virus.', 1976),
(u'Death of Mao Zedong.', 1976),
(u'End of Cultural Revolution.', 1976),
(u'Church Committee.', 1976),
(u'Elvis Presley dies.', 1977),
(u'Shaba I conflict involves Safari Club.', 1977),
(u'Invention of artificial insulin.', 1978),
(u"Discovery of Pluto's moon Charon.", 1978),
(u'Independence of Tuvalu.', 1978),
(u'Birth of the first test-tube baby.', 1978),
(u'Cambodian-Vietnamese War begins.', 1978),
(u'Uganda\u2013Tanzania War begins.', 1978),
(u'War in Afghanistan (1978\u2013present) begins.', 1978),
(u'Spanish transition to democracy is completed.', 1978),
(u'John Paul I and then John Paul II become Pope.', 1978),
(u'Smallpox eradicated.', 1979),
(u'Soviet\u2013Afghan War begins.', 1979),
(u'Rhodesian Bush War ends.', 1979),
(u'Iranian Revolution and Iran hostage crisis.', 1979),
(u'Shah Reza Pahlavi forced into exile.', 1979),
(u'First close-up images of Saturn.', 1979),
(u"Implementation of China's One child policy.", 1979),
(u'Sino-Vietnamese War.', 1979),
(u'Nicaraguan Revolution.', 1979),
(u'Central Treaty Organization dissolved.', 1979),
(u'Independence of Rhodesia, which becomes Zimbabwe.', 1980),
(u'Independence of Vanuatu.', 1980),
(u'1980 eruption of Mount St. Helens.', 1980),
(u'Queen Beatrix becomes monarch of the Netherlands.', 1980),
(u'Disappearance and death of Azaria Chamberlain.', 1980),
(u'Death of John Lennon.', 1980),
(u'Independence of Palau.', 1981),
(u'First orbital flight of the Space Shuttle.', 1981),
(u'Assassination of Anwar Sadat.', 1981),
(u'First Israeli invasion of Lebanon.', 1982),
(u'Falklands War.', 1982),
(u'Independence of Brunei.', 1983),
(u'End of dictatorship in Argentina.', 1983),
(u'Second Sudanese Civil War begins.', 1983),
(u'Invasion of Grenada by the United States.', 1983),
(u'Bombing of U.S. Embassy in Beirut.', 1983),
(u'Assassination of Indira Gandhi.', 1984),
(u'End of 1982 Lebanon War.Live Aid.', 1985),
(u'First use of DNA fingerprinting.', 1985),
(u'End of military leadership in Brazil.', 1985),
(u'Challenger and Chernobyl disasters.', 1986),
(u'South Yemen Civil War.', 1986),
(u'Launch of the space station Mir.', 1986),
(u'First close up images of the planet Uranus.', 1986),
(u"Return of Halley's Comet.", 1986),
(u'Iran-Contra becomes public.', 1986),
(u'Assassination of Olof Palme.', 1986),
(u'Stock market crash of 1987.', 1987),
(u'World population reaches 5 billion.', 1987),
(u'Perestroika begins.', 1988),
(u'End of the Iran-Iraq War.', 1988),
(u'End of dictatorship of Augusto Pinochet in Chile.', 1988),
(u'Pan Am Flight 103 falls over Lockerbie, Scotland.', 1988),
(u'Myanmar Armed Forces launch a military coup.', 1988),
(u'Construction of the Channel Tunnel begins.', 1988),
(u'Tiananmen Square Massacre in China.', 1989),
(u'End of Soviet\u2013Afghan War.', 1989),
(u'Fatwa issued against Salman Rushdie.', 1989),
(u'Exxon Valdez oil spill.', 1989),
(u'First close up pictures of Neptune.', 1989),
(u'First Liberian Civil War begins.', 1989),
(u'Death of Salvador Dal\xed.', 1989),
(u'Sir Tim Berners-Lee invents the World Wide Web.', 1990),
(u'German reunification.', 1990),
(u'Launch of the Hubble Space Telescope.', 1990),
(u'Gulf War begins.', 1990),
(u'Contra War ends.', 1990),
(u'Ten-Day War in Slovenia begins the Yugoslav Wars.', 1991),
(u'Final end of the Khmer Rouge in Cambodia.', 1991),
(u'Maastricht Treaty creates the European Union.', 1992),
(u'End of dictatorship in Albania and South Korea.', 1992),
(u'End of Salvadorian Civil War.', 1992),
(u'Bosnian War begins.', 1992),
(u'Independence of Eritrea.', 1993),
(u'1993 World Trade Center bombing.', 1993),
(u'First Chechen War begins.', 1994),
(u'1994 civil war in Yemen.', 1994),
(u'Opening of the Channel Tunnel.', 1994),
(u'Death of Kim Il-sung.', 1994),
(u'Kim Jong-Il becomes Supreme Leader of North Korea.', 1994),
(u'Death of Kurt Cobain.', 1994),
(u'Establishment of the World Trade Organization.', 1995),
(u'Srebrenica massacre.', 1995),
(u'Assassination of Yitzhak Rabin.', 1995),
(u'North Korean famine begins.', 1995),
(u'Third Taiwan Strait Crisis begins.', 1995),
(u'First Congo War begins.', 1996),
(u'Third Taiwan Strait Crisis ends.', 1996),
(u'First Chechen War ends.', 1996),
(u'First Liberian Civil War ends.', 1996),
(u'End of dictatorship in Taiwan.', 1996),
(u'Nepalese Civil War begins.', 1996),
(u'Lottery Uprising in Albania.', 1997),
(u'Sound barrier broken on land.', 1997),
(u'Kenya and Tanzania bombings.', 1998),
(u'Google is founded by Larry Page and Sergey Brin.', 1998),
(u'Second Congo War begins.', 1998),
(u'Euro is introduced.', 1999),
(u'Kosovo War ends the Yugoslav Wars.', 1999),
(u'Islamist insurgency in Nigeria begins.', 1999),
(u'Hugo Chavez becomes President of Venezuela.', 1999),
(u'Fourth Indo-Pakistani War.', 1999),
(u'Crisis in East Timor leads to 1400 deaths.', 1999),
(u'3rd millennium celebrations.', 2000),
(u'End of Israeli occupation of Lebanon.', 2000),
(u'Second Intifada begins.', 2000),
(u'Vladimir Putin becomes President of Russia.', 2000),
(u'International Space Station begins operations.', 2000),
(u'First Inter-Korean Summit.', 2000),
(u'al-Qaeda suicide bombs the USS\xa0Cole.', 2000),
(u'War on Terror declared.', 2001),
(u'Afghan War begins.', 2001),
(u'Wikipedia founded.', 2001),
(u'African Union founded.', 2001),
(u'2002 Bali bombings.', 2002),
(u'Chechen rebels seize theatre in Moscow.', 2002),
(u'Guantanamo Bay detention camp is established.', 2002),
(u'Algerian Civil War ends.', 2002),
(u'Beltway sniper attacks.', 2002),
(u'Rose Revolution in Georgia.', 2002),
(u'Independence of East Timor.', 2002),
(u'Iraq War begins, triggering worldwide protests.', 2003),
(u'War in Darfur begins.', 2003),
(u'The Human Genome Project is completed.', 2003),
(u'Second Liberian Civil War ends.', 2003),
(u'Space Shuttle Columbia is destroyed on re-entry.', 2003),
(u'Union of South American Nations formed.', 2004),
(u'Madrid train bombings.', 2004),
(u'Orange Revolution in Ukraine.', 2004),
(u'Beslan school hostage crisis.', 2004),
(u'Death of Ronald Reagan and Yasser Arafat.', 2004),
(u'IRA end military campaign in Northern Ireland.', 2005),
(u'7/7 attacks on London Underground.', 2005),
(u'Tulip Revolution in Kyrgyzstan.', 2005),
(u'Second Intifada ends.', 2005),
(u'Israel withdraws from Gaza.', 2005),
(u'Second Sudanese Civil War ends.', 2005),
(u'80,000 are killed in an earthquake in Kashmir.', 2005),
(u'The Kyoto Protocol comes into effect.', 2005),
(u'Mahmoud Ahmadinejad becomes President of Iran.', 2005),
(u'Mike Brown discovers Eris.', 2005),
(u'Independence of Montenegro.', 2006),
(u'2006 Lebanon War.', 2006),
(u'Mumbai bombings.', 2006),
(u'Execution of Saddam Hussein.', 2006),
(u'Assassination of Benazir Bhutto.', 2007),
(u'End of Monarchy in Nepal.', 2008),
(u'Cyclone Nargis kills 133,000 in Myanmar.', 2008),
(u'Gaza War begins.', 2008),
(u'2008 South Ossetia war.', 2008),
(u'Kosovo declares independence, to mixed reaction.', 2008),
(u'2008 Mumbai attacks.', 2008),
(u'Gaza War ends; Gaza blockade continues.', 2009),
(u'Sri Lankan Civil War ends.', 2009),
(u'Election protests begin in Iran.', 2009),
(u'Second Chechen War ends.', 2009),
(u'Boko Haram rebellion begins in Nigeria.', 2009),
(u'Death of Michael Jackson.', 2009),
(u'Great Recession officially ends.', 2009),
(u'Formation of BRICS economic bloc.', 2009),
(u'Treaty of Lisbon ratified.', 2009),
(u'A 7.0 magnitude earthquake in Haiti kills 230,000.', 2010),
(u'North Korea shells the island of Yeonpyeong.', 2010),
(u'Aung San Suu Kyi released from house arrest.', 2010),
(u'2010 Moscow Metro bombings.', 2010),
(u'2010 Kyrgyzstani revolution.', 2010),
(u"2010 Nigerien coup d'\xe9tat.", 2010),
(u'Independence of South Sudan.', 2011),
(u'Syrian civil war begins.', 2011),
(u'Occupy movement inspires worldwide protests.', 2011),
(u'News International phone hacking scandal.', 2011),
(u'Iraq War ends.', 2011),
(u'Riots flare across England.', 2011),
(u'Bombings occur In Russia and Somalia.', 2011),
(u'World population reaches 7 billion.', 2011),
(u'Death of Steve Jobs.', 2011),
(u'Yemeni President Ali Abdullah Saleh steps down.', 2012),
(u'The Higgs boson is discovered.', 2012),
(u'Conflict begins in the Central African Republic.', 2012),
(u"2012 Guinea-Bissau coup d'\xe9tat.", 2012),
(u'Chelyabinsk meteor.', 2013),
(u'Terrorist attacks occur in Boston and Nairobi.', 2013),
(u'2013 Savar building collapse in Bangladesh.', 2013),
(u'Croatia becomes a member of the European Union.', 2013),
(u'The Euromaidan protest begins in Ukraine.', 2013),
(u'Conflict begins in South Sudan.', 2013),
(u'End of 2012\u20132013 Cypriot financial crisis.', 2013),
(u'Second Libyan Civil War begins.', 2014)]
