HISTORY = [(u'Boxer Rebellion ends.', 1901),
(u'Assassination of William McKinley.', 1901),
(u'Second Boer War ends.', 1902),
(u'Philippine\u2013American War ends.', 1902),
(u'Cuba gains independence from the United States.', 1902),
(u'Unification of Saudi Arabia begins.', 1902),
(u'Pius X becomes Pope.', 1903),
(u'The teddy bear is invented.', 1903),
(u'The first Tour de France is held.', 1903),
(u'Trans-Siberian railway is completed.', 1904),
(u'Construction of the Panama Canal begins.', 1904),
(u'End of British expedition to Tibet.', 1904),
(u'Russo-Japanese War ends.', 1905),
(u'Revolution of 1905 in Russia.', 1905),
(u'Persian Constitutional Revolution begins.', 1905),
(u'Trans-Siberian Railway opened.', 1905),
(u"Albert Einstein's formulation of relativity.", 1905),
(u'Schlieffen Plan proposed.', 1905),
(u'First Moroccan Crisis.', 1905),
(u'Dreyfus Affair ends.', 1906),
(u'Death of Paul C\xe9zanne.', 1906),
(u'The US began the Second Occupation of Cuba.', 1906),
(u'Herero and Namaqua Genocide ends.', 1907),
(u'Japan\u2013Korea Treaty of 1907.', 1907),
(u'First commercial radio transmissions.', 1908),
(u'Young Turk Revolution in the Ottoman Empire.', 1908),
(u'Independence of Bulgaria.', 1908),
(u'1908 Messina earthquake kills over 70,000 people.', 1908),
(u'United States troops leave Cuba.', 1909),
(u'Anglo-Siamese Treaty of 1909.', 1909),
(u'Ottoman countercoup fails in the Ottoman Empire.', 1909),
(u'Japan and China sign the Jiandao/Gando Treaty.', 1909),
(u'Beginning of the Mexican Revolution.', 1910),
(u'Union of South Africa created.', 1910),
(u'Imperial Japan annexes Korea.', 1910),
(u'Deaths of Leo Tolstoy and Mark Twain.', 1910),
(u'Boy Scouts of America is founded.', 1910),
(u"Halley's Comet returns.", 1910),
(u'Montenegro is proclaimed an independent kingdom.', 1910),
(u'Albanian Revolt of 1910.', 1910),
(u'Roald Amundsen first reaches the South Pole.', 1911),
(u'New Delhi becomes the capital of British India.', 1911),
(u'Ernest Rutherford identifies the atomic nucleus.', 1911),
(u'Agadir Crisis.', 1911),
(u'The African National Congress is founded.', 1912),
(u'Morocco becomes a protectorate of France.', 1912),
(u'Sinking of the RMS Titanic.', 1912),
(u'First Balkan War begin.', 1912),
(u'United States occupation of Nicaragua begins.', 1912),
(u'La Decena Tr\xe1gica.', 1913),
(u'Treaty of London.', 1913),
(u'Second Balkan War and Treaty of Bucharest.', 1913),
(u'The Federal Reserve System is created.', 1913),
(u'Panama Canal opens.', 1914),
(u'Benedict XV becomes Pope.', 1914),
(u'Martha, last known passenger pigeon, dies.', 1914),
(u'The RMS Lusitania is sunk.', 1915),
(u'The United States occupation of Haiti begins.', 1915),
(u'Armenian genocide in the Ottoman Empire.', 1915),
(u'Easter Rising in Ireland.', 1916),
(u'The implementation of daylight saving time.', 1916),
(u'Warlord Era begins in China.', 1916),
(u'The Gallipoli Campaign fails.', 1916),
(u'Battle of the Somme.', 1916),
(u'Battle of Verdun.', 1916),
(u'The Arab Revolt begins.', 1916),
(u'The first Pulitzer Prizes are awarded.', 1917),
(u'October Revolution in Russia.', 1917),
(u'End of World War I. German Revolution begins.', 1918),
(u'Murder of Tsar Nicholas II and his family.', 1918),
(u'Finnish Civil War.', 1918),
(u'Partitioning of the Ottoman Empire begins.', 1918),
(u'The British occupy Palestine.', 1918),
(u'Mutawakkilite Kingdom of Yemen is founded.', 1918),
(u'Azerbaijan Democratic Republic is declared.', 1918),
(u'Armenian\u2013Azerbaijani War begins.', 1918),
(u'Treaty of Versailles redraws European borders.', 1919),
(u'Turkish War of Independence begins.', 1919),
(u'League of Nations founded in Paris.', 1919),
(u'Polish-Soviet War begins.', 1919),
(u'Comintern established.', 1919),
(u'Egyptian Revolution of 1919.', 1919),
(u'Turkish War of Independence begins.', 1919),
(u'Ernest Rutherford discovers the proton.', 1919),
(u'Mexican Revolution ends.', 1920),
(u'Greece restores its monarchy after a referendum.', 1920),
(u'Mohandas Gandhi launches Non-cooperation movement.', 1920),
(u'Prohibition in the United States enforced.', 1920),
(u'End of Russian Civil War and Polish-Soviet War.', 1921),
(u'Coup brings the Pahlavi dynasty to power in Iran.', 1921),
(u'The Irish Civil War begins.', 1922),
(u'The Italian reconquest of Libya begins.', 1922),
(u"Howard Carter discovers Tutankhamen's tomb.", 1922),
(u'Pius XI becomes Pope.', 1922),
(u'James Joyce publishes Ulysses.', 1922),
(u'The Washington Naval Treaty is signed.', 1922),
(u'Time Magazine is first published.', 1923),
(u'Irish Civil War ends.', 1923),
(u'The Walt Disney Company is founded.', 1923),
(u'The Caliphate is abolished by Kamal Atat\xfcrk.', 1924),
(u'George Gershwin composes Rhapsody In Blue.', 1924),
(u'Mein Kampf is published.', 1925),
(u'Locarno Treaties are signed.', 1925),
(u'Serum run to Nome.', 1925),
(u'Hirohito becomes Emperor of Japan.', 1926),
(u'The Jazz Singer, the first "talkie", is released.', 1927),
(u'Joseph Stalin becomes leader of the Soviet Union.', 1927),
(u'Chinese Civil War begins.', 1927),
(u'Bath School disaster.', 1927),
(u'Saudi Arabia gains independence.', 1927),
(u'World population reaches 2 billion.', 1927),
(u"Charles Lindbergh's flight to Paris.", 1927),
(u'Discovery of penicillin by Alexander Fleming.', 1928),
(u'Warlord Era ends in China.', 1928),
(u'Malta becomes a British Dominion.', 1928),
(u'King Zog I is crowned in Albania.', 1928),
(u'The Kellogg-Briand Pact is signed in Paris.', 1928),
(u'Mickey Mouse is created at the Walt Disney Studio.', 1928),
(u'Hassan al-Banna founds the Muslim Brotherhood.', 1928),
(u'Vatican City is recognised as a sovereign state.', 1929),
(u"Saint Valentine's Day Massacre.", 1929),
(u'The first Academy Awards are presented.', 1929),
(u'Clyde Tombaugh discovers Pluto.', 1930),
(u'Haile Selassie becomes king of Abyssinia.', 1930),
(u'First FIFA World Cup hosted.', 1930),
(u'Floods in China kill up to 2.5 million people.', 1931),
(u'Independence of South Africa.', 1931),
(u'Construction of the Empire State Building.', 1931),
(u'The Second Spanish Republic is declared.', 1931),
(u'Military coup in Chile.', 1932),
(u'BBC World Service starts broadcasting.', 1932),
(u'The Neutron is discovered.', 1932),
(u'Adolf Hitler becomes Chancellor of Germany.', 1933),
(u'New Deal begins in America.', 1933),
(u'United States occupation of Nicaragua ends.', 1933),
(u'Dictatorships begin in Brazil and Bolivia.', 1934),
(u'Mao Zedong begins the Long March.', 1934),
(u'United States occupation of Haiti ends.', 1934),
(u'Persia becomes Iran.', 1935),
(u'Enactment of the Nuremberg racial laws.', 1935),
(u'Beginning of the Spanish Civil War.', 1936),
(u'Great Purge begins under Stalin.', 1936),
(u'Italy annexes Ethiopia.', 1936),
(u'Rape of Nanking.', 1937),
(u'Deaths of George Gershwin and Maurice Ravel.', 1937),
(u'Anschluss unifies Germany and Austria.', 1938),
(u'Great Purge ends after nearly 700,000 executions.', 1938),
(u'DC Comics hero Superman has its first appearance.', 1938),
(u'Soviet invasion of Poland begins 16 days later.', 1939),
(u'Palestinian revolt against the British ends.', 1939),
(u'Pius XII becomes Pope.', 1939),
(u'Winter War between Soviet Union and Finland.', 1940),
(u'Soviet Union annexes the Baltic states.', 1940),
(u'The Blitz begins.', 1940),
(u'Leon Trotsky is assassinated.', 1940),
(u'Chechen insurgency begins in Soviet Union.', 1940),
(u'Siege of Leningrad begins.', 1941),
(u'Battle of Midway.', 1942),
(u'Battle of the Coral Sea.', 1942),
(u'First and second Battles of El Alamein.', 1942),
(u'Manhattan Project begins.', 1942),
(u'Warsaw Ghetto uprising fails.', 1943),
(u'Green Revolution begins.', 1943),
(u'D-Day.', 1944),
(u'Bombing of Dresden.', 1945),
(u'Battle of Berlin.', 1945),
(u'Yalta Conference.', 1945),
(u'End of World War II in Europe.', 1945),
(u'United Nations founded.', 1945),
(u'Independence of Korea.', 1945),
(u'Deaths of Anne Frank and B\xe9la Bart\xf3k.', 1945),
(u'Independence of Indonesia.', 1945),
(u'Nuremberg trials begin.', 1945),
(u'Italy becomes a republic.', 1946),
(u'French Fourth Republic established.', 1946),
(u'Independence of Jordan.', 1946),
(u'Nuremberg trials end.', 1946),
(u'First Indochina War begins.', 1946),
(u'First images taken of the Earth from space.', 1946),
(u'Bhumibol Adulyadej becomes King of Thailand.', 1946),
(u'Treaty of Manila declares Philippines independent.', 1946),
(u'Invention of the first practical transistor.', 1947),
(u'Breaking of the sound barrier.', 1947),
(u'Creation of the U.S. Central Intelligence Agency.', 1947),
(u'Arab-Israeli War.', 1948),
(u'Berlin Blockade begins.', 1948),
(u'Assassination of Mohandas Gandhi.', 1948),
(u'The independence of Burma.', 1948),
(u'Beginning of apartheid in South Africa.', 1948),
(u'Division of North and South Korea.', 1948),
(u'First Indo-Pakistani War ends.', 1948),
(u'Creation of NATO. Berlin Blockade ends.', 1949),
(u'COMECON founded by USSR and the Eastern Bloc.', 1949),
(u'Partition of Kashmir.', 1949),
(u'Soviet Union tests atomic bomb.', 1949),
(u'Beginning of the Korean War.', 1950),
(u'Colombo Plan comes into effect.', 1951),
(u'European Defence Community formed.', 1952),
(u'Slansky Trial in Czechoslovakia.', 1952),
(u'Detonation of the hydrogen bomb.', 1952),
(u'First scheduled flight by commercial jet.', 1952),
(u'Mau Mau Uprising begins in Kenya.', 1952),
(u'Independence of Cambodia.', 1953),
(u'Discovery of DNA. First ascent of Mount Everest.', 1953),
(u'Mohammed Mossadeq deposed in Iran.', 1953),
(u'End of the Korean War.', 1953),
(u"Elvis Presley's musical career is launched.", 1953),
(u'First Indochina War ends.', 1954),
(u'Algerian War begins.', 1954),
(u'First Taiwan Strait Crisis begins.', 1954),
(u'Signing of the Warsaw Pact.', 1955),
(u'First Sudanese Civil War begins.', 1955),
(u'First Taiwan Strait Crisis ends.', 1955),
(u'Antimatter first produced.', 1955),
(u'Formation of the Central Treaty Organization.', 1955),
(u'French Fifth Republic established.', 1956),
(u'The Hungarian Uprising crushed by Soviet troops.', 1956),
(u'Brasilia constructed.', 1956),
(u'Independence of Ghana.', 1957),
(u'Harold Macmillan become British Prime Minister.', 1957),
(u'Great Chinese Famine begins in China.', 1958),
(u"CND's symbol, the peace sign, is first used.", 1958),
(u'Second Taiwan Strait Crisis.', 1958),
(u'Cuban Revolution.', 1959),
(u'Independence of Cyprus and Singapore.', 1959),
(u'First documented AIDS cases.', 1959),
(u'Beginning of the Vietnam War.', 1959),
(u'First images of the far side of the Moon.', 1959),
(u'World population reaches 3 billion.', 1959),
(u'European Free Trade Association formed.', 1960),
(u'Sharpeville Massacre in South Africa.', 1960),
(u'Mau Mau Uprising ends.', 1960),
(u'Construction of the first laser.', 1960),
(u'The Beatles form in Liverpool.', 1960),
(u'Muhammad Ali wins gold in Rome.', 1960),
(u'Construction of the Berlin Wall.', 1961),
(u'First human spaceflight.', 1961),
(u'Cuban missile crisis.', 1962),
(u'Death of Marilyn Monroe.', 1962),
(u'Indonesia\u2013Malaysia confrontation begins.', 1962),
(u'North Yemen Civil War begins.', 1962),
(u'Sino-Indian War.', 1962),
(u'Martin Luther King, Jr.', 1963),
(u'Assassination of John F. Kennedy.', 1963),
(u'Launch of the first geostationary satellite.', 1963),
(u'Paul VI becomes Pope.', 1963),
(u'Independence of Malta, Malawi and Tanzania.', 1964),
(u'Rhodesian Bush War begins.', 1964),
(u'First close-up images of Mars.', 1964),
(u'Second Indo-Pakistani War.', 1965),
(u'Second Vatican Council is closed by Pope Paul VI.', 1965),
(u'Indonesia\u2013Malaysia confrontation ends.', 1966),
(u"China's Cultural Revolution begins.", 1966),
(u'Independence of Lesotho, Botswana and Barbados.', 1966),
(u'Summer of Love.', 1967),
(u'Six Day War.', 1967),
(u'ASEAN founded.', 1967),
(u'Assassinations of Martin Luther King, Jr.', 1968),
(u'May 1968 protests in France.', 1968),
(u'The Troubles begin in Northern Ireland.', 1968),
(u'Tet Offensive occurs in South Vietnam.', 1968),
(u'Moon landings.', 1969),
(u'Woodstock festival.', 1969),
(u'Sino-Soviet border conflict.', 1969),
(u'Polish 1970 protests.', 1970),
(u'Cambodian Civil War begins.', 1970),
(u'Yemeni Civil War ends.', 1970),
(u'Maiden flight of the Boeing 747.', 1970),
(u'Black September in Jordan begins.', 1970),
(u'Death of Gamal Abdel Nasser.', 1970),
(u'Anwar Sadat becomes President of Egypt.', 1970),
(u'Deaths of Jimi Hendrix and Janis Joplin.', 1970),
(u'Black September in Jordan ends.', 1971),
(u'Internment begins in Northern Ireland.', 1971),
(u'Invention of the microchip.', 1971),
(u'Idi Amin seizes power in Uganda.', 1971),
(u'Greenpeace founded.', 1971),
(u'COINTELPRO officially ends.', 1971),
(u"Northern Ireland's Bloody Sunday.", 1972),
(u'First Sudanese Civil War ends.', 1972),
(u"1973 Chilean coup d'\xe9tat.", 1973),
(u'First space station, Skylab, is launched.', 1973),
(u'Wade.', 1973),
(u'Death of Pablo Picasso.', 1973),
(u'First close-up images of Jupiter.', 1973),
(u'Turkish occupation of Cyprus.', 1974),
(u'First close-up images of Mercury.', 1974),
(u'World population reaches 4 billion.', 1974),
(u'Resignation of Richard Nixon.', 1974),
(u'End of Vietnam War and Fall of Saigon.', 1975),
(u'Haile Selassie I dies in mysterious circumstances.', 1975),
(u'Dmitri Shostakovich dies.', 1975),
(u'The Killing Fields murders begin.', 1975),
(u'First Cricket World Cup hosted.', 1975),
(u'First outbreak of the Ebola virus.', 1976),
(u'Death of Mao Zedong.', 1976),
(u'End of Cultural Revolution.', 1976),
(u'Church Committee.', 1976),
(u'Elvis Presley dies.', 1977),
(u'Shaba I conflict involves Safari Club.', 1977),
(u'Invention of artificial insulin.', 1978),
(u"Discovery of Pluto's moon Charon.", 1978),
(u'Independence of Tuvalu.', 1978),
(u'Birth of the first test-tube baby.', 1978),
(u'Cambodian-Vietnamese War begins.', 1978),
(u'Uganda\u2013Tanzania War begins.', 1978),
(u'War in Afghanistan (1978\u2013present) begins.', 1978),
(u'Spanish transition to democracy is completed.', 1978),
(u'John Paul I and then John Paul II become Pope.', 1978),
(u'Smallpox eradicated.', 1979),
(u'Soviet\u2013Afghan War begins.', 1979),
(u'Rhodesian Bush War ends.', 1979),
(u'Iranian Revolution and Iran hostage crisis.', 1979),
(u'Shah Reza Pahlavi forced into exile.', 1979),
(u'First close-up images of Saturn.', 1979),
(u"Implementation of China's One child policy.", 1979),
(u'Sino-Vietnamese War.', 1979),
(u'Nicaraguan Revolution.', 1979),
(u'Central Treaty Organization dissolved.', 1979),
(u'Independence of Rhodesia, which becomes Zimbabwe.', 1980),
(u'Independence of Vanuatu.', 1980),
(u'1980 eruption of Mount St. Helens.', 1980),
(u'Queen Beatrix becomes monarch of the Netherlands.', 1980),
(u'Death of John Lennon.', 1980),
(u'Independence of Palau.', 1981),
(u'First orbital flight of the Space Shuttle.', 1981),
(u'Assassination of Anwar Sadat.', 1981),
(u'First Israeli invasion of Lebanon.', 1982),
(u'Falklands War.', 1982),
(u'GPS becomes available for civilian use.', 1983),
(u'Independence of Brunei.', 1983),
(u'End of dictatorship in Argentina.', 1983),
(u'Second Sudanese Civil War begins.', 1983),
(u'Invasion of Grenada by the United States.', 1983),
(u'Bombing of U.S. Embassy in Beirut.', 1983),
(u'Assassination of Indira Gandhi.', 1984),
(u'End of 1982 Lebanon War.Live Aid.', 1985),
(u'First use of DNA fingerprinting.', 1985),
(u'End of military leadership in Brazil.', 1985),
(u'Challenger and Chernobyl disasters.', 1986),
(u'South Yemen Civil War.', 1986),
(u'Launch of the space station Mir.', 1986),
(u'First close up images of the planet Uranus.', 1986),
(u"Return of Halley's Comet.", 1986),
(u'Iran-Contra becomes public.', 1986),
(u'Assassination of Olof Palme.', 1986),
(u'Stock market crash of 1987.', 1987),
(u'World population reaches 5 billion.', 1987),
(u'Perestroika begins.', 1988),
(u'End of the Iran-Iraq War.', 1988),
(u'End of dictatorship of Augusto Pinochet in Chile.', 1988),
(u'Pan Am Flight 103 falls over Lockerbie, Scotland.', 1988),
(u'Myanmar Armed Forces launch a military coup.', 1988),
(u'Construction of the Channel Tunnel begins.', 1988),
(u'Tiananmen Square Massacre in China.', 1989),
(u'End of Soviet\u2013Afghan War.', 1989),
(u'Fatwa issued against Salman Rushdie.', 1989),
(u'Exxon Valdez oil spill.', 1989),
(u'First close up pictures of Neptune.', 1989),
(u'First Liberian Civil War begins.', 1989),
(u'Death of Salvador Dal\xed.', 1989),
(u'Sir Tim Berners-Lee invents the World Wide Web.', 1990),
(u'German reunification.', 1990),
(u'Launch of the Hubble Space Telescope.', 1990),
(u'Gulf War begins.', 1990),
(u'Contra War ends.', 1990),
(u'Ten-Day War in Slovenia begins the Yugoslav Wars.', 1991),
(u'Final end of the Khmer Rouge in Cambodia.', 1991),
(u'Maastricht Treaty creates the European Union.', 1992),
(u'End of dictatorship in Albania and South Korea.', 1992),
(u'End of Salvadorian Civil War.', 1992),
(u'Bosnian War begins.', 1992),
(u'Independence of Eritrea.', 1993),
(u'1993 World Trade Center bombing.', 1993),
(u'Waco siege.', 1993),
(u'First Chechen War begins.', 1994),
(u'1994 civil war in Yemen.', 1994),
(u'Opening of the Channel Tunnel.', 1994),
(u'Death of Kim Il-sung.', 1994),
(u'Kim Jong-Il becomes Supreme Leader of North Korea.', 1994),
(u'Death of Kurt Cobain.', 1994),
(u'Establishment of the World Trade Organization.', 1995),
(u'Srebrenica massacre.', 1995),
(u'Assassination of Yitzhak Rabin.', 1995),
(u'North Korean famine begins.', 1995),
(u'Third Taiwan Strait Crisis begins.', 1995),
(u'First Congo War begins.', 1996),
(u'Third Taiwan Strait Crisis ends.', 1996),
(u'First Chechen War ends.', 1996),
(u'First Liberian Civil War ends.', 1996),
(u'End of dictatorship in Taiwan.', 1996),
(u'Lottery Uprising in Albania.', 1997),
(u'Sound barrier broken on land.', 1997),
(u'Kenya and Tanzania bombings.', 1998),
(u'Second Congo War begins.', 1998),
(u'Euro is introduced.', 1999),
(u'Kosovo War ends the Yugoslav Wars.', 1999),
(u'Islamist insurgency in Nigeria begins.', 1999),
(u'Hugo Chavez becomes President of Venezuela.', 1999),
(u'Fourth Indo-Pakistani War.', 1999),
(u'Crisis in East Timor leads to 1400 deaths.', 1999),
(u'3rd millennium celebrations.', 2000),
(u'End of Israeli occupation of Lebanon.', 2000),
(u'Second Intifada begins.', 2000),
(u'Vladimir Putin becomes President of Russia.', 2000),
(u'International Space Station begins operations.', 2000),
(u'First Inter-Korean Summit.', 2000),
(u'al-Qaeda suicide bombs the USS\xa0Cole.', 2000),
(u'Afghan War begins.', 2001),
(u'Wikipedia founded.', 2001),
(u'African Union founded.', 2001),
(u'2002 Bali bombings.', 2002),
(u'Chechen rebels seize theatre in Moscow.', 2002),
(u'Guantanamo Bay detention camp is established.', 2002),
(u'Algerian Civil War ends.', 2002),
(u'Rose Revolution in Georgia.', 2002),
(u'Independence of East Timor.', 2002),
(u'Iraq War begins, triggering worldwide protests.', 2003),
(u'War in Darfur begins.', 2003),
(u'The Human Genome Project is completed.', 2003),
(u'Second Liberian Civil War ends.', 2003),
(u'Space Shuttle Columbia is destroyed on re-entry.', 2003),
(u'Union of South American Nations formed.', 2004),
(u'Madrid train bombings.', 2004),
(u'Orange Revolution in Ukraine.', 2004),
(u'Beslan school hostage crisis.', 2004),
(u'Death of Ronald Reagan and Yasser Arafat.', 2004),
(u'IRA end military campaign in Northern Ireland.', 2005),
(u'7/7 attacks on London Underground.', 2005),
(u'Tulip Revolution in Kyrgyzstan.', 2005),
(u'Second Intifada ends.', 2005),
(u'Israel withdraws from Gaza.', 2005),
(u'Second Sudanese Civil War ends.', 2005),
(u'80,000 are killed in an earthquake in Kashmir.', 2005),
(u'The Kyoto Protocol comes into effect.', 2005),
(u'Mahmoud Ahmadinejad becomes President of Iran.', 2005),
(u'Discovery of Eris.', 2005),
(u'Independence of Montenegro.', 2006),
(u'2006 Lebanon War.', 2006),
(u'Mumbai bombings.', 2006),
(u'Execution of Saddam Hussein.', 2006),
(u'Assassination of Benazir Bhutto.', 2007),
(u'End of Monarchy in Nepal.', 2008),
(u'Cyclone Nargis kills 133,000 in Myanmar.', 2008),
(u'Gaza War begins.', 2008),
(u'2008 South Ossetia war.', 2008),
(u'Kosovo declares independence, to mixed reaction.', 2008),
(u'Gaza War ends; Gaza blockade continues.', 2009),
(u'Sri Lankan Civil War ends.', 2009),
(u'Election protests begin in Iran.', 2009),
(u'Second Chechen War ends.', 2009),
(u'Boko Haram rebellion begins in Nigeria.', 2009),
(u'Death of Michael Jackson.', 2009),
(u'Great Recession officially ends.', 2009),
(u'Formation of BRICS economic bloc.', 2009),
(u'Treaty of Lisbon ratified.', 2009),
(u'A 7.0 magnitude earthquake in Haiti kills 230,000.', 2010),
(u'North Korea shells the island of Yeonpyeong.', 2010),
(u'Aung San Suu Kyi released from house arrest.', 2010),
(u'2010 Moscow Metro bombings.', 2010),
(u'2010 Kyrgyzstani revolution.', 2010),
(u"2010 Nigerien coup d'\xe9tat.", 2010),
(u'Death of Steve Jobs.', 2011),
(u'Independence of South Sudan.', 2011),
(u'Syrian civil war begins.', 2011),
(u'Occupy movement inspires worldwide protests.', 2011),
(u'News International phone hacking scandal.', 2011),
(u'Iraq War ends.', 2011),
(u'Riots flare across England.', 2011),
(u'World population reaches 7 billion.', 2011),
(u'Yemeni President Ali Abdullah Saleh steps down.', 2012),
(u'The Higgs boson is discovered.', 2012),
(u"2012 Guinea-Bissau coup d'\xe9tat.", 2012),
(u'Chelyabinsk meteor.', 2013),
(u'Terrorist attacks occur in Boston and Nairobi.', 2013),
(u'2013 Savar building collapse in Bangladesh.', 2013),
(u'Croatia becomes a member of the European Union.', 2013),
(u'The Euromaidan protest begins in Ukraine.', 2013),
(u'Conflict begins in South Sudan.', 2013),
(u'End of 2012\u20132013 Cypriot financial crisis.', 2013)]
