# Generated by Django 3.1.2 on 2020-10-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gedgo', '0003_auto_20150404_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(upload_to='uploaded'),
        ),
        migrations.AlterField(
            model_name='document',
            name='kind',
            field=models.CharField(choices=[('DOCUM', 'Document'), ('VIDEO', 'Video'), ('PHOTO', 'Image')], max_length=5),
        ),
        migrations.AlterField(
            model_name='document',
            name='thumb',
            field=models.FileField(blank=True, null=True, upload_to='uploaded/thumbs'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_approxQ',
            field=models.BooleanField(verbose_name='Date is approximate'),
        ),
        migrations.AlterField(
            model_name='family',
            name='kind',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Event'),
        ),
    ]
